export const SELECT_STUDENT = 'SELECT_STUDENT';
export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCESS = 'ADD_STUDENT_SUCESS';
export const LIST_STUDENTS_REQUEST = 'LIST_STUDENTS_REQUEST';
export const LIST_STUDENTS_SUCESS = 'LIST_STUDENTS_SUCESS';
export const SHOW_NAVBAR = 'SHOW_NAVBAR';
