export const SELECT_STUDENT = 'SELECT_STUDENT';
export const CLEAR_SELECTED_STUDENT = 'CLEAR_SELECTED_STUDENT';
export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST';
export const ADD_STUDENT_SUCESS = 'ADD_STUDENT_SUCESS';
export const LIST_STUDENTS_REQUEST = 'LIST_STUDENTS_REQUEST';
export const LIST_STUDENTS_SUCESS = 'LIST_STUDENTS_SUCESS';
export const SHOW_NAVBAR = 'SHOW_NAVBAR';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_OUT = 'SIGN_OUT';

export const ADD_TEACHER_REQUEST = 'ADD_TEACHER_REQUEST';
export const ADD_TEACHER_SUCESS = 'ADD_TEACHER_SUCESS';
